var mobileSettings = {
    introTubsScale:0.4,
    gameLogoScale:0.6,
    logoScale:0.7,
    btnScale:0.7,
    instructionsScale:0.55,
    instructionOffset:50,
    reindeerScale:0.4,
    reindeerSpacing:40,
    santaScale:0.35,
    tubsScale:0.5,
    tubsOffset:10,
    houseScale:0.7,
    houseOffset:60,
    giftScale:0.7,
    uiScale:0.5,
    uiFont:"16px Arial",
    uiFontPosition:43,
    scoreOffset:50,
    timerOffset:130,
    houseGapMin:50,
    houseGapMax:100,
    splashHeadingFont:'42px Arial',
    playBtnFont:'30px Helvetica',
    instructionDescFont:'23px Arial',
    shareHeadingTop: 170,
    scoreTextFont:'60px Arial',
    finalScoreTextFont:'35px Arial',
    "instructions":"Use the arrow buttons to move up & down. To drop presents, tap A",
    "endTubsScale":0.5,
    "endTubsPc":100,
    "shareY":90,
    "shareScale":0.6,
    "shareSpacing":50
};

var desktopSettings = {
    introTubsScale:0.8,
    gameLogoScale:1,
    logoScale:1,
    btnScale:0.8,
    instructionsScale:1,
    instructionOffset:100,
    reindeerScale:0.7,
    reindeerSpacing:60,
    santaScale:0.55,
    houseScale:1,
    houseOffset:6,
    giftScale:1,
    uiScale:1,
    uiFont:"30px Arial",
    uiFontPosition:73,
    scoreOffset:100,
    timerOffset:250,
    houseGapMin:150,
    houseGapMax:200,
    tubsScale:0.75,
    tubsOffset:20,
    splashHeadingFont:'42px Arial',
    playBtnFont:'30px Helvetica',
    instructionDescFont:'23px Arial',
    shareHeadingTop: 170,
    scoreTextFont:'60px Arial',
    finalScoreTextFont:'35px Arial',
    "instructions":"Use the up/down arrows to move and press Space to drop presents",
    "endTubsScale":1,
    "endTubsPc":20,
    "shareY":95,
    "shareScale":1,
    "shareSpacing":100
};

var settings = mobileSettings;
